
export default class MarketInformation {

  constructor(LOW, HIGH, TIME, BID, ASK, POINT, DIGITS, 
    SPREAD, STOPLEVEL, LOTSIZE, TICKVALUE, TICKSIZE, 
    SWAPLONG, SWAPSHORT, STARTING, EXPIRATION, 
    TRADEALLOWED, MINLOT, LOTSTEP, MAXLOT, SWAPTYPE, 
    PROFITCALCMODE, MARGINCALCMODE, MARGININIT, 
    MARGINMAINTENANCE, MARGINHEDGED, MARGINREQUIRED, 
    FREEZELEVEL) {
    this.LOW = LOW;
    this.HIGH = HIGH;
    this.TIME = TIME;
    this.BID = BID;
    this.ASK = ASK;
    this.POINT = POINT;
    this.DIGITS = DIGITS;
    this.SPREAD = SPREAD;
    this.STOPLEVEL = STOPLEVEL;
    this.LOTSIZE = LOTSIZE;
    this.TICKVALUE = TICKVALUE;
    this.TICKSIZE = TICKSIZE;
    this.SWAPLONG = SWAPLONG;
    this.SWAPSHORT = SWAPSHORT;
    this.STARTING = STARTING;
    this.EXPIRATION = EXPIRATION;
    this.TRADEALLOWED = TRADEALLOWED;
    this.MINLOT = MINLOT;
    this.LOTSTEP = LOTSTEP;
    this.MAXLOT = MAXLOT;
    this.SWAPTYPE = SWAPTYPE;
    this.PROFITCALCMODE = PROFITCALCMODE;
    this.MARGINCALCMODE = MARGINCALCMODE;
    this.MARGININIT = MARGININIT;
    this.MARGINMAINTENANCE = MARGINMAINTENANCE;
    this.MARGINHEDGED = MARGINHEDGED;
    this.MARGINREQUIRED = MARGINREQUIRED;
    this.FREEZELEVEL = FREEZELEVEL;;
  }
}